app/models/user.py
from app import db, ma, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), unique=True, nullable=False)
    pwd = db.Column(db.String(200), nullable=False)

    def __init__(self, name, email, pwd):
        self.name = name
        self.email = email
        self.pwd = generate_password_hash(pwd)

    @property
    def password(self):
        raise AttributeError('Não é possível acessar a senha do usuário')

    def verify_password(self, pwd):
        return check_password_hash(self.pwd, pwd)

    def __repr__(self):
        return '<User: {}>'.format(self.name)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))


class UserSchema(ma.Schema):
    class Meta:
        fields = ('id', 'name', 'email', 'pwd')


user_schema = UserSchema()
users_schema = UserSchema(many=True)

app/__init__.py
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_marshmallow import Marshmallow
from flask_paranoid import Paranoid
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from dotenv import load_dotenv


APP_ROOT = os.path.join(os.path.dirname(__file__), '..')
dotenv_path = os.path.join(APP_ROOT, '.env')
load_dotenv(dotenv_path)
app = Flask(__name__)
paranoid = Paranoid(app)
paranoid.redirect_view = '/'
app.config.from_object('config')

Bootstrap(app)

db = SQLAlchemy(app)
ma = Marshmallow(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.session_protection = "strong"
login_manager.login_message = "You must be logged in to access this page"
login_manager.login_view = "auth.login"

from .models import user

from .admin import admin as admin_blueprint
app.register_blueprint(admin_blueprint, url_prefix='/admin')

from .auth import auth as auth_blueprint
app.register_blueprint(auth_blueprint)

from .home import home as home_blueprint
app.register_blueprint(home_blueprint)

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template
from flask_login import login_required
from . import home


@home.route('/')
def homepage():
    return render_template('home/index.html', title='Welcome')


@home.route('/dashboard')
@login_required
def dashboard():
    return render_template('home/dashboard.html', title='Users')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }} | Hackathon Test</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Hackathon Test - Evandro Morini</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                  <li><a href="{{ url_for('home.dashboard') }}">Dashboard</a></li>
                  <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                  <li><a><i class="fa fa-user"></i>  Hi, {{ current_user.name }}!</a></li>
                {% else %}
                  <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                  <li><a href="{{ url_for('auth.register') }}">Register</a></li>
                  <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                {% endif %}
              </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
</body>
</html>

app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Success</h1>
                    <h3>Usuário logado com sucesso!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Rentcars Hackathon</h1>
                    <h3>Evandro Morini</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}